import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { DataTable } from "./DataTable";
import { NestedDataStoreProvider } from "../../data/nestedDataStore/NestedDataStoreProvider";
import type { ColumnDefinition, TableData } from "./types";

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Returns the Nth nested DataTable element (0-indexed) by finding the "Company"
 * column headers, which only exist in nested tables (the outer test table never
 * has a "Company" header). Re-query after every open/close cycle — portals unmount
 * on close so stale references will fail.
 */
function getNestedTable(level: number): HTMLElement {
  const companyHeaders = screen.getAllByRole("columnheader", {
    name: "Company",
  });
  return companyHeaders[level].closest("table") as HTMLElement;
}

/**
 * Returns the "More" popper cell (column 2) from the first data row of a nested
 * table. The nested table columns are: [Company (0), Revenue (1), More (2)].
 */
function getMoreCell(table: HTMLElement): HTMLElement {
  // rows[0] = header, rows[1] = first data row
  const rows = within(table).getAllByRole("row");
  return within(rows[1]).getAllByRole("cell")[2] as HTMLElement;
}

/**
 * Selects a PopperCell, enters editing mode (button focused), and opens its
 * popover by pressing Enter. Assumes the cell is not currently selected.
 *
 * Interaction sequence for PopperCell:
 *   click 1 → onSelect  (cell becomes selected)
 *   click 2 → onEdit    (button gets focus)
 *   Enter   → popover opens
 */
async function openPopperCell(
  user: ReturnType<typeof userEvent.setup>,
  cell: HTMLElement,
) {
  await user.click(cell); // select
  await user.click(cell); // enter editing, button receives focus
  await user.keyboard("{Enter}"); // open popover
}

/**
 * Enters editing mode on the auto-selected cell (0,0), replaces its text with
 * `value`, and commits via Tab (which calls onExitEdit + onNavigate("next")).
 *
 * When a DataTable wrapper first receives external focus, handleFocus auto-selects
 * (0,0). Radix auto-focuses the DataTable wrapper when PopoverContent mounts, so
 * (0,0) is selected immediately after any popover opens.
 */
async function editFirstCell(
  user: ReturnType<typeof userEvent.setup>,
  value: string,
) {
  await user.keyboard("{Enter}"); // enter editing for auto-selected (0,0)
  await user.clear(screen.getByRole("textbox"));
  await user.type(screen.getByRole("textbox"), value);
  await user.keyboard("{Tab}"); // commit and exit editing
}

// ─── Fixtures ─────────────────────────────────────────────────────────────────

// Outer table: one text column and one popper column.
// The popper's nested DataTable is generated by PopperCell on first open.
// That nested DataTable itself contains a "More" popper column, enabling 3+ levels.
const outerColumns: ColumnDefinition[] = [
  { key: "name", header: "Name", type: "text" },
  { key: "info", header: "Info", type: "popper", triggerText: "Open" },
];

// A single row with an `id` field so NestedDataStore can build stable path keys
// using the format `rowId:colKey` (e.g. "outer-r1:info").
const outerData: TableData[] = [
  { id: "outer-r1", name: "Row 1", info: "row 1 info" },
];

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("DataTable deep-chain nested DataTable persistence", () => {
  it("preserves edits at all 3 levels after closing and reopening all poppers", async () => {
    const user = userEvent.setup();
    render(
      <NestedDataStoreProvider>
        <DataTable columns={outerColumns} data={outerData} />
      </NestedDataStoreProvider>,
    );

    // ── Open level 1 ──────────────────────────────────────────────────────────
    // The outer table has 1 data row × 2 cols: name=[0], info=[1].
    const outerInfoCell = screen.getAllByRole("cell")[1];
    await openPopperCell(user, outerInfoCell);

    // Level 1 popover is open. Radix auto-focuses the nested DataTable wrapper
    // → handleFocus auto-selects (0,0) → Enter enters editing → type + Tab commits.
    await editFirstCell(user, "level-1-edit");

    // ── Open level 2 ──────────────────────────────────────────────────────────
    // The nested table has columns [Company, Revenue, More]. "More" is col 2 of row 0.
    // After editFirstCell, cell (0,1) is selected (Tab moved there). We click the
    // "More" cell at (0,2) to open the level-2 popover.
    await openPopperCell(user, getMoreCell(getNestedTable(0)));
    await editFirstCell(user, "level-2-edit");

    // ── Open level 3 ──────────────────────────────────────────────────────────
    await openPopperCell(user, getMoreCell(getNestedTable(1)));
    await editFirstCell(user, "level-3-edit");

    // ── Close all levels ──────────────────────────────────────────────────────
    // Radix DismissableLayer intercepts Escape at the document level and closes
    // the innermost open popover on each press. DataTable's own Escape handler
    // deselects the active cell, but does not stop propagation, so Radix also
    // receives the event and closes the portal.
    await user.keyboard("{Escape}"); // close level 3
    await user.keyboard("{Escape}"); // close level 2
    await user.keyboard("{Escape}"); // close level 1

    // After all three closes the outer DataTable's wrapper has focus and the
    // "info" popper cell is in "selected" mode (onExitEdit reverts from editing).

    // ── Reopen level 1 and verify edit persisted ───────────────────────────────
    // Enter 1: DataTable's handleKeyDown enters "editing" mode → useEffect focuses button.
    // Enter 2: button's native click opens the popover (useCellKeyboard does not
    //          intercept Enter for PopperCell because enterNavigates=false).
    await user.keyboard("{Enter}"); // enter editing mode on "info" cell
    await user.keyboard("{Enter}"); // open level 1 popover

    // Re-query getNestedTable after reopen — the portal remounted.
    // Cell (0,0) in the nested table is the "Company" column of the first data row.
    expect(within(getNestedTable(0)).getAllByRole("cell")[0]).toHaveTextContent(
      "level-1-edit",
    );

    // ── Reopen level 2 and verify ─────────────────────────────────────────────
    await openPopperCell(user, getMoreCell(getNestedTable(0)));
    expect(within(getNestedTable(1)).getAllByRole("cell")[0]).toHaveTextContent(
      "level-2-edit",
    );

    // ── Reopen level 3 and verify ─────────────────────────────────────────────
    await openPopperCell(user, getMoreCell(getNestedTable(1)));
    expect(within(getNestedTable(2)).getAllByRole("cell")[0]).toHaveTextContent(
      "level-3-edit",
    );
  });
});
